name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.x"

      - name: Instalar pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Ejecutar tests
        run: pytest

      - name: Feedback con Slack para éxito
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ Build y tests exitosos en la rama '${{ github.ref_name }}' - Commit: ${{ github.sha }}"}' \
            $SLACK_WEBHOOK_URL

      - name: Feedback con Slack en caso de fallo
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ Build o tests fallaron en la rama '${{ github.ref_name }}' - Commit: ${{ github.sha }}"}' \
            $SLACK_WEBHOOK_URL