name: CI/CD

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:

  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.x"

      - name: Instalar pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Ejecutar tests
        run: pytest

      - name: Feedback con Slack para éxito en PR
        if: success() && github.event_name == 'pull_request'
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"✅ CI: Build y tests exitosos.\n${{github.actor}} realizó un ${{github.event_name}} desde la rama ${{github.head_ref}} a la rama ${{github.base_ref}}\"}" \
            $SLACK_WEBHOOK_URL

      - name: Feedback con Slack para éxito en commit
        if: success() && github.event_name == 'push'
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"✅ CI: Build y tests exitosos en la rama ${{github.ref_name}}\n${{github.actor}} realizó un ${{github.event_name}}\"}" \
            $SLACK_WEBHOOK_URL

      - name: Feedback con Slack en caso de fallo
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"❌ CI: Build o tests fallaron en la rama ${{github.ref_name}}\n${{github.actor}} intentó realizar un ${{github.event_name}}\"}" \
            $SLACK_WEBHOOK_URL

  cd:
    name: Continuous Deployment
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref_name == 'main' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.x"

      - name: Ejecutar script como parte del despliegue
        run: |
          python maquina_expendedora_ICS.py

      - name: Feedback con Slack para CD
        if: success()
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"✅ CD: Nueva versión de la Maquina Expendedora disponible !\"}" \
            $SLACK_WEBHOOK_URL